### ISSUE TITLE
[Fabric 1.20.1] Unidye cant start on server

### ISSUE THREAD

**Issue by agung-wijaya** [DiemondPlayer/Unidye#4]
Minecraft Version 1.20.1
Fabric loader for server 0.16.9
I want contribute but still new for this, please warn me if I do wrong

Unidye instaled
[2024-11-01-5.log](https://github.com/user-attachments/files/17596869/2024-11-01-5.log)

Unidye uninstaled
[2024-11-01-7.log](https://github.com/user-attachments/files/17596872/2024-11-01-7.log)

**Comment by DiemondPlayer** [comment]
Hello! Thank you for reporting the issue. I am trying to understand what can be wrong. In the meantime, does the modpack run on client? Also, the second log still contains errors regarding unidye, even when it is uninstalled, are you sure you uploaded the right file?

**Comment by DiemondPlayer** [comment]
Try loading this version of the mod, I changed a few lines, maybe it will work. I cannot test it myself since I don't have a server to test it on. You need to unzip the archive because I cannot send .jars through GitHub. Please report to me whether this version will work.
[UnidyeTestFix.zip](https://github.com/user-attachments/files/17597103/UnidyeTestFix.zip)

**Comment by agung-wijaya** [comment]
I found problems while instal with REI, JEI, and EMI
It cannot join server
[latest (6).log](https://github.com/user-attachments/files/17598420/latest.6.log)
If instal with JEI, client will crash

I make modpack for fun, might it would help for test it
https://drive.google.com/file/d/1dnJEcpAwW7BKBJAn9hpcmJyQYGXzZzUr/view?usp=drive_link

**Comment by DiemondPlayer** [comment]
I know this may sound like a dumb question but, is your unidye version the same on client and server? because this is 1.0.0 version but your server has 1.0.0TestFix version. 

I will investigate further in my free time, but as far as I know Unidye works with REI perfectly fine. I do not know about JEI though.

![image](https://github.com/user-attachments/assets/abfb1dd2-16a6-4ede-8db2-950d0b0f4866)


![image](https://github.com/user-attachments/assets/afdaa84a-d75b-41a4-9b3e-816574a0519d)

**Comment by agung-wijaya** [comment]
![image](https://github.com/user-attachments/assets/cc18aff8-b6f5-4625-bfdf-54b5441596e0)
![image](https://github.com/user-attachments/assets/95cb19de-302c-4694-a3f7-74f91f8afb33)

yes, might it will help.

**Comment by DiemondPlayer** [comment]
Hello again! This is not a problem with compatibility, the mod crashes by itself in the multiplayer. I am trying to fix this. I will update you if I fix it. Sorry for the inconvinience.

**Comment by DiemondPlayer** [comment]
Fixed it! You can download the 1.1.0 update on modrinth or curseforge! And also the mod does not crash with JEI anymore!
